spring.datasource.url=mysql://root:bBIWSrxxQyFwSFYWYCWkbTbRiGQNRqgx@mysql.railway.internal:3306/railwaymysql://root:bBIWSrxxQyFwSFYWYCWkbTbRiGQNRqgx@maglev.proxy.rlwy.net:54038/railway
spring.datasource.username=root
spring.datasource.password=bBIWSrxxQyFwSFYWYCWkbTbRiGQNRqgx
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect